/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function MaleHairThree(props) {
	const group = useRef();
	const { nodes, materials, animations } = useGLTF("/MaleHairThree.glb");
	const { actions } = useAnimations(animations, group);
	return (
		<group ref={group} {...props} dispose={null}>
			<group name="Male_A">
				<group name="Male_A_1" position={[672.34, 0, -127.25]} scale={1.03}>
					<group
						name="Character"
						position={[0, 0.86, 0]}
						rotation={[-Math.PI / 2, 0, -1.57]}
					>
						<group name="Character_Pelvis" rotation={[-Math.PI / 2, 0, -1.57]}>
							<group
								name="Character_L_Thigh"
								position={[0, 0, 0.11]}
								rotation={[3.14, -0.04, 3.06]}
							>
								<group name="Character_L_Calf" position={[0.4, 0, 0]}>
									<group
										name="Character_L_Foot"
										position={[0.38, 0, 0]}
										rotation={[-0.21, -0.06, 0.07]}
									>
										<group
											name="Character_L_Toe0"
											position={[0.07, 0.11, 0]}
											rotation={[0, 0, Math.PI / 2]}
										/>
									</group>
								</group>
							</group>
							<group
								name="Character_R_Thigh"
								position={[0, 0, -0.11]}
								rotation={[-3.14, 0.04, 3.06]}
							>
								<group name="Character_R_Calf" position={[0.4, 0, 0]}>
									<group
										name="Character_R_Foot"
										position={[0.38, 0, 0]}
										rotation={[0.21, 0.06, 0.07]}
									>
										<group
											name="Character_R_Toe0"
											position={[0.07, 0.11, 0]}
											rotation={[0, 0, Math.PI / 2]}
										/>
									</group>
								</group>
							</group>
							<group
								name="Character_Spine"
								position={[0.05, 0.02, 0]}
								rotation={[0, 0, -0.11]}
							>
								<group
									name="Character_Spine1"
									position={[0.18, 0, 0]}
									rotation={[0, 0, 0.06]}
								>
									<group
										name="Character_Spine2"
										position={[0.18, 0, 0]}
										rotation={[0, 0, -0.19]}
									>
										<group
											name="Character_L_Clavicle"
											position={[0.15, -0.01, 0.04]}
											rotation={[0.16, 1.26, 3.14]}
										>
											<group
												name="Character_L_UpperArm"
												position={[0.17, 0, 0]}
												rotation={[0.19, 0.54, -0.02]}
											>
												<group
													name="Character_L_Forearm"
													position={[0.25, 0, 0]}
													rotation={[0, 0, -0.23]}
												>
													<group
														name="Character_L_Hand"
														position={[0.21, 0, 0]}
														rotation={[-1.31, 0.01, 0.24]}
													>
														<group
															name="Character_L_Finger0"
															position={[0.02, 0, -0.02]}
															rotation={[1.44, 0.46, -0.66]}
														>
															<group
																name="Character_L_Finger01"
																position={[0.05, 0, 0]}
																rotation={[0, 0, 0.17]}
															>
																<group
																	name="Character_L_Finger02"
																	position={[0.03, 0, 0]}
																	rotation={[0, 0, -0.13]}
																/>
															</group>
														</group>
														<group
															name="Character_L_Finger1"
															position={[0.11, 0, -0.03]}
															rotation={[0, 0.06, 0.14]}
														>
															<group
																name="Character_L_Finger11"
																position={[0.03, 0, 0]}
																rotation={[0, 0, 0.16]}
															>
																<group
																	name="Character_L_Finger12"
																	position={[0.03, 0, 0]}
																	rotation={[0, 0, 0.16]}
																/>
															</group>
														</group>
														<group
															name="Character_L_Finger2"
															position={[0.12, 0, 0]}
															rotation={[0, -0.05, 0.28]}
														>
															<group
																name="Character_L_Finger21"
																position={[0.03, 0, 0]}
																rotation={[0, 0, 0.17]}
															>
																<group
																	name="Character_L_Finger22"
																	position={[0.02, 0, 0]}
																	rotation={[0, 0, 0.06]}
																/>
															</group>
														</group>
														<group
															name="Character_L_Finger3"
															position={[0.11, 0, 0.02]}
															rotation={[0, -0.12, 0.23]}
														>
															<group
																name="Character_L_Finger31"
																position={[0.03, 0, 0]}
																rotation={[0, 0, 0.23]}
															>
																<group
																	name="Character_L_Finger32"
																	position={[0.03, 0, 0]}
																	rotation={[0, 0, 0.23]}
																/>
															</group>
														</group>
														<group
															name="Character_L_Finger4"
															position={[0.1, 0, 0.05]}
															rotation={[0, -0.34, 0.27]}
														>
															<group
																name="Character_L_Finger41"
																position={[0.02, 0, 0]}
																rotation={[0, 0, 0.23]}
															>
																<group
																	name="Character_L_Finger42"
																	position={[0.02, 0, 0]}
																	rotation={[0, 0, 0.23]}
																/>
															</group>
														</group>
													</group>
												</group>
											</group>
										</group>
										<group
											name="Character_Neck"
											position={[0.18, 0, 0]}
											rotation={[0, 0, 0.53]}
										>
											<group
												name="Character_Head"
												position={[0.1, 0, 0]}
												rotation={[0, 0, -0.28]}
											>
												<mesh
													name="Set_Character_Character_Head_Male_Hair_4"
													castShadow
													receiveShadow
													geometry={
														nodes.Set_Character_Character_Head_Male_Hair_4
															.geometry
													}
													material={materials.Male_Hair_4}
													scale={0.97}
												/>
											</group>
										</group>
										<group
											name="Character_R_Clavicle"
											position={[0.15, -0.01, -0.04]}
											rotation={[-0.16, -1.26, 3.14]}
										>
											<group
												name="Character_R_UpperArm"
												position={[0.17, 0, 0]}
												rotation={[-0.19, -0.54, -0.02]}
											>
												<group
													name="Character_R_Forearm"
													position={[0.25, 0, 0]}
													rotation={[0, 0, -0.23]}
												>
													<group
														name="Character_R_Hand"
														position={[0.21, 0, 0]}
														rotation={[1.31, -0.01, 0.24]}
													>
														<group
															name="Character_R_Finger0"
															position={[0.02, 0, 0.02]}
															rotation={[-1.44, -0.46, -0.66]}
														>
															<group
																name="Character_R_Finger01"
																position={[0.05, 0, 0]}
																rotation={[0, 0, 0.17]}
															>
																<group
																	name="Character_R_Finger02"
																	position={[0.03, 0, 0]}
																	rotation={[0, 0, -0.13]}
																/>
															</group>
														</group>
														<group
															name="Character_R_Finger1"
															position={[0.11, 0, 0.03]}
															rotation={[0, -0.06, 0.14]}
														>
															<group
																name="Character_R_Finger11"
																position={[0.03, 0, 0]}
																rotation={[0, 0, 0.16]}
															>
																<group
																	name="Character_R_Finger12"
																	position={[0.03, 0, 0]}
																	rotation={[0, 0, 0.16]}
																/>
															</group>
														</group>
														<group
															name="Character_R_Finger2"
															position={[0.12, 0, 0]}
															rotation={[0, 0.05, 0.28]}
														>
															<group
																name="Character_R_Finger21"
																position={[0.03, 0, 0]}
																rotation={[0, 0, 0.17]}
															>
																<group
																	name="Character_R_Finger22"
																	position={[0.02, 0, 0]}
																	rotation={[0, 0, 0.06]}
																/>
															</group>
														</group>
														<group
															name="Character_R_Finger3"
															position={[0.11, 0, -0.02]}
															rotation={[0, 0.12, 0.23]}
														>
															<group
																name="Character_R_Finger31"
																position={[0.03, 0, 0]}
																rotation={[0, 0, 0.23]}
															>
																<group
																	name="Character_R_Finger32"
																	position={[0.03, 0, 0]}
																	rotation={[0, 0, 0.23]}
																/>
															</group>
														</group>
														<group
															name="Character_R_Finger4"
															position={[0.1, 0, -0.05]}
															rotation={[0, 0.34, 0.27]}
														>
															<group
																name="Character_R_Finger41"
																position={[0.02, 0, 0]}
																rotation={[0, 0, 0.23]}
															>
																<group
																	name="Character_R_Finger42"
																	position={[0.02, 0, 0]}
																	rotation={[0, 0, 0.23]}
																/>
															</group>
														</group>
													</group>
												</group>
											</group>
										</group>
									</group>
								</group>
							</group>
						</group>
					</group>
					<group name="Set_Character_Male_Hair_4" scale={0.97} />
				</group>
			</group>
		</group>
	);
}

useGLTF.preload("/MaleHairThree.glb");
