/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function MaleC(props) {
	const group = useRef();
	const { nodes, materials, animations } = useGLTF("/MaleC.glb");
	const { actions } = useAnimations(animations, group);

	// useEffect(() => {
	// 	actions[names[4]].reset().play();
	// }, [props.hairTypeSelection]);

	return (
		<group ref={group} {...props} dispose={null}>
			<group name="Male_C_(1)" position={[0, -0.9, 0]}>
				<group name="Male_C_(1)_1">
					<group
						name="Character"
						position={[0, 0.86, 0]}
						rotation={[-Math.PI / 2, 0, -1.57]}
					>
						<group name="Character_Pelvis" rotation={[-Math.PI / 2, 0, -1.57]}>
							<group
								name="Character_L_Thigh"
								position={[0, 0, 0.11]}
								rotation={[3.14, -0.04, 3.06]}
							>
								<group name="Character_L_Calf" position={[0.4, 0, 0]}>
									<group
										name="Character_L_Foot"
										position={[0.38, 0, 0]}
										rotation={[-0.21, -0.06, 0.07]}
									>
										<group
											name="Character_L_Toe0"
											position={[0.07, 0.11, 0]}
											rotation={[0, 0, Math.PI / 2]}
										>
											<primitive
												object={
													nodes.Set_Character_Character_L_Toe0_Male_Legs_1
												}
											/>
										</group>
										<primitive
											object={nodes.Set_Character_Character_L_Foot_Male_Legs_1}
										/>
									</group>
									<primitive
										object={nodes.Set_Character_Character_L_Calf_Male_Legs_1}
									/>
								</group>
								<primitive
									object={nodes.Set_Character_Character_L_Thigh_Male_Legs_1}
								/>
								<primitive
									object={nodes.Set_Character_Character_L_Thigh_Male_Torso_1}
								/>
							</group>
							<group
								name="Character_R_Thigh"
								position={[0, 0, -0.11]}
								rotation={[-3.14, 0.04, 3.06]}
							>
								<group name="Character_R_Calf" position={[0.4, 0, 0]}>
									<group
										name="Character_R_Foot"
										position={[0.38, 0, 0]}
										rotation={[0.21, 0.06, 0.07]}
									>
										<group
											name="Character_R_Toe0"
											position={[0.07, 0.11, 0]}
											rotation={[0, 0, Math.PI / 2]}
										>
											<primitive
												object={
													nodes.Set_Character_Character_R_Toe0_Male_Legs_1
												}
											/>
										</group>
										<primitive
											object={nodes.Set_Character_Character_R_Foot_Male_Legs_1}
										/>
									</group>
									<primitive
										object={nodes.Set_Character_Character_R_Calf_Male_Legs_1}
									/>
								</group>
								<primitive
									object={nodes.Set_Character_Character_R_Thigh_Male_Legs_1}
								/>
								<primitive
									object={nodes.Set_Character_Character_R_Thigh_Male_Torso_1}
								/>
							</group>
							<group
								name="Character_Spine"
								position={[0.05, 0.02, 0]}
								rotation={[0, 0, -0.11]}
							>
								<group
									name="Character_Spine1"
									position={[0.18, 0, 0]}
									rotation={[0, 0, 0.06]}
								>
									<group
										name="Character_Spine2"
										position={[0.18, 0, 0]}
										rotation={[0, 0, -0.19]}
									>
										<group
											name="Character_L_Clavicle"
											position={[0.15, -0.01, 0.04]}
											rotation={[0.16, 1.26, 3.14]}
										>
											<group
												name="Character_L_UpperArm"
												position={[0.17, 0, 0]}
												rotation={[0.19, 0.54, -0.02]}
											>
												<group
													name="Character_L_Forearm"
													position={[0.25, 0, 0]}
													rotation={[0, 0, -0.23]}
												>
													<group
														name="Character_L_Hand"
														position={[0.21, 0, 0]}
														rotation={[-1.31, 0.01, 0.24]}
													>
														<group
															name="Character_L_Finger0"
															position={[0.02, 0, -0.02]}
															rotation={[1.44, 0.46, -0.66]}
														>
															<group
																name="Character_L_Finger01"
																position={[0.05, 0, 0]}
																rotation={[0, 0, 0.17]}
															>
																<group
																	name="Character_L_Finger02"
																	position={[0.03, 0, 0]}
																	rotation={[0, 0, -0.13]}
																>
																	<primitive
																		object={
																			nodes.Set_Character_Character_L_Finger02_Male_Torso_1
																		}
																	/>
																</group>
																<primitive
																	object={
																		nodes.Set_Character_Character_L_Finger01_Male_Torso_1
																	}
																/>
															</group>
															<primitive
																object={
																	nodes.Set_Character_Character_L_Finger0_Male_Torso_1
																}
															/>
														</group>
														<group
															name="Character_L_Finger1"
															position={[0.11, 0, -0.03]}
															rotation={[0, 0.06, 0.14]}
														>
															<group
																name="Character_L_Finger11"
																position={[0.03, 0, 0]}
																rotation={[0, 0, 0.16]}
															>
																<group
																	name="Character_L_Finger12"
																	position={[0.03, 0, 0]}
																	rotation={[0, 0, 0.16]}
																>
																	<primitive
																		object={
																			nodes.Set_Character_Character_L_Finger12_Male_Torso_1
																		}
																	/>
																</group>
																<primitive
																	object={
																		nodes.Set_Character_Character_L_Finger11_Male_Torso_1
																	}
																/>
															</group>
															<primitive
																object={
																	nodes.Set_Character_Character_L_Finger1_Male_Torso_1
																}
															/>
														</group>
														<group
															name="Character_L_Finger2"
															position={[0.12, 0, 0]}
															rotation={[0, -0.05, 0.28]}
														>
															<group
																name="Character_L_Finger21"
																position={[0.03, 0, 0]}
																rotation={[0, 0, 0.17]}
															>
																<group
																	name="Character_L_Finger22"
																	position={[0.02, 0, 0]}
																	rotation={[0, 0, 0.06]}
																>
																	<primitive
																		object={
																			nodes.Set_Character_Character_L_Finger22_Male_Torso_1
																		}
																	/>
																</group>
																<primitive
																	object={
																		nodes.Set_Character_Character_L_Finger21_Male_Torso_1
																	}
																/>
															</group>
															<primitive
																object={
																	nodes.Set_Character_Character_L_Finger2_Male_Torso_1
																}
															/>
														</group>
														<group
															name="Character_L_Finger3"
															position={[0.11, 0, 0.02]}
															rotation={[0, -0.12, 0.23]}
														>
															<group
																name="Character_L_Finger31"
																position={[0.03, 0, 0]}
																rotation={[0, 0, 0.23]}
															>
																<group
																	name="Character_L_Finger32"
																	position={[0.03, 0, 0]}
																	rotation={[0, 0, 0.23]}
																>
																	<primitive
																		object={
																			nodes.Set_Character_Character_L_Finger32_Male_Torso_1
																		}
																	/>
																</group>
																<primitive
																	object={
																		nodes.Set_Character_Character_L_Finger31_Male_Torso_1
																	}
																/>
															</group>
															<primitive
																object={
																	nodes.Set_Character_Character_L_Finger3_Male_Torso_1
																}
															/>
														</group>
														<group
															name="Character_L_Finger4"
															position={[0.1, 0, 0.05]}
															rotation={[0, -0.34, 0.27]}
														>
															<group
																name="Character_L_Finger41"
																position={[0.02, 0, 0]}
																rotation={[0, 0, 0.23]}
															>
																<group
																	name="Character_L_Finger42"
																	position={[0.02, 0, 0]}
																	rotation={[0, 0, 0.23]}
																>
																	<primitive
																		object={
																			nodes.Set_Character_Character_L_Finger42_Male_Torso_1
																		}
																	/>
																</group>
																<primitive
																	object={
																		nodes.Set_Character_Character_L_Finger41_Male_Torso_1
																	}
																/>
															</group>
															<primitive
																object={
																	nodes.Set_Character_Character_L_Finger4_Male_Torso_1
																}
															/>
														</group>
														<primitive
															object={
																nodes.Set_Character_Character_L_Hand_Male_Torso_1
															}
														/>
													</group>
													<primitive
														object={
															nodes.Set_Character_Character_L_Forearm_Male_Torso_1
														}
													/>
												</group>
												<primitive
													object={
														nodes.Set_Character_Character_L_UpperArm_Male_Torso_1
													}
												/>
											</group>
											<primitive
												object={
													nodes.Set_Character_Character_L_Clavicle_Male_Torso_1
												}
											/>
										</group>
										<group
											name="Character_Neck"
											position={[0.18, 0, 0]}
											rotation={[0, 0, 0.53]}
										>
											<group
												name="Character_Head"
												position={[0.1, 0, 0]}
												rotation={[0, 0, -0.28]}
											>
												<primitive
													object={
														nodes.Set_Character_Character_Head_Male_Torso_1
													}
												/>
												<primitive
													object={
														nodes.Set_Character_Character_Head_Male_Head_1
													}
												/>
											</group>
											<primitive
												object={nodes.Set_Character_Character_Neck_Male_Torso_1}
											/>
										</group>
										<group
											name="Character_R_Clavicle"
											position={[0.15, -0.01, -0.04]}
											rotation={[-0.16, -1.26, 3.14]}
										>
											<group
												name="Character_R_UpperArm"
												position={[0.17, 0, 0]}
												rotation={[-0.19, -0.54, -0.02]}
											>
												<group
													name="Character_R_Forearm"
													position={[0.25, 0, 0]}
													rotation={[0, 0, -0.23]}
												>
													<group
														name="Character_R_Hand"
														position={[0.21, 0, 0]}
														rotation={[1.31, -0.01, 0.24]}
													>
														<group
															name="Character_R_Finger0"
															position={[0.02, 0, 0.02]}
															rotation={[-1.44, -0.46, -0.66]}
														>
															<group
																name="Character_R_Finger01"
																position={[0.05, 0, 0]}
																rotation={[0, 0, 0.17]}
															>
																<group
																	name="Character_R_Finger02"
																	position={[0.03, 0, 0]}
																	rotation={[0, 0, -0.13]}
																>
																	<primitive
																		object={
																			nodes.Set_Character_Character_R_Finger02_Male_Torso_1
																		}
																	/>
																</group>
																<primitive
																	object={
																		nodes.Set_Character_Character_R_Finger01_Male_Torso_1
																	}
																/>
															</group>
															<primitive
																object={
																	nodes.Set_Character_Character_R_Finger0_Male_Torso_1
																}
															/>
														</group>
														<group
															name="Character_R_Finger1"
															position={[0.11, 0, 0.03]}
															rotation={[0, -0.06, 0.14]}
														>
															<group
																name="Character_R_Finger11"
																position={[0.03, 0, 0]}
																rotation={[0, 0, 0.16]}
															>
																<group
																	name="Character_R_Finger12"
																	position={[0.03, 0, 0]}
																	rotation={[0, 0, 0.16]}
																>
																	<primitive
																		object={
																			nodes.Set_Character_Character_R_Finger12_Male_Torso_1
																		}
																	/>
																</group>
																<primitive
																	object={
																		nodes.Set_Character_Character_R_Finger11_Male_Torso_1
																	}
																/>
															</group>
															<primitive
																object={
																	nodes.Set_Character_Character_R_Finger1_Male_Torso_1
																}
															/>
														</group>
														<group
															name="Character_R_Finger2"
															position={[0.12, 0, 0]}
															rotation={[0, 0.05, 0.28]}
														>
															<group
																name="Character_R_Finger21"
																position={[0.03, 0, 0]}
																rotation={[0, 0, 0.17]}
															>
																<group
																	name="Character_R_Finger22"
																	position={[0.02, 0, 0]}
																	rotation={[0, 0, 0.06]}
																>
																	<primitive
																		object={
																			nodes.Set_Character_Character_R_Finger22_Male_Torso_1
																		}
																	/>
																</group>
																<primitive
																	object={
																		nodes.Set_Character_Character_R_Finger21_Male_Torso_1
																	}
																/>
															</group>
															<primitive
																object={
																	nodes.Set_Character_Character_R_Finger2_Male_Torso_1
																}
															/>
														</group>
														<group
															name="Character_R_Finger3"
															position={[0.11, 0, -0.02]}
															rotation={[0, 0.12, 0.23]}
														>
															<group
																name="Character_R_Finger31"
																position={[0.03, 0, 0]}
																rotation={[0, 0, 0.23]}
															>
																<group
																	name="Character_R_Finger32"
																	position={[0.03, 0, 0]}
																	rotation={[0, 0, 0.23]}
																>
																	<primitive
																		object={
																			nodes.Set_Character_Character_R_Finger32_Male_Torso_1
																		}
																	/>
																</group>
																<primitive
																	object={
																		nodes.Set_Character_Character_R_Finger31_Male_Torso_1
																	}
																/>
															</group>
															<primitive
																object={
																	nodes.Set_Character_Character_R_Finger3_Male_Torso_1
																}
															/>
														</group>
														<group
															name="Character_R_Finger4"
															position={[0.1, 0, -0.05]}
															rotation={[0, 0.34, 0.27]}
														>
															<group
																name="Character_R_Finger41"
																position={[0.02, 0, 0]}
																rotation={[0, 0, 0.23]}
															>
																<group
																	name="Character_R_Finger42"
																	position={[0.02, 0, 0]}
																	rotation={[0, 0, 0.23]}
																>
																	<primitive
																		object={
																			nodes.Set_Character_Character_R_Finger42_Male_Torso_1
																		}
																	/>
																</group>
																<primitive
																	object={
																		nodes.Set_Character_Character_R_Finger41_Male_Torso_1
																	}
																/>
															</group>
															<primitive
																object={
																	nodes.Set_Character_Character_R_Finger4_Male_Torso_1
																}
															/>
														</group>
														<primitive
															object={
																nodes.Set_Character_Character_R_Hand_Male_Torso_1
															}
														/>
														<mesh
															name="Sword_1"
															castShadow
															receiveShadow
															geometry={nodes.Sword_1.geometry}
															material={materials.Sword_1_Yellow}
														/>
													</group>
													<primitive
														object={
															nodes.Set_Character_Character_R_Forearm_Male_Torso_1
														}
													/>
												</group>
												<primitive
													object={
														nodes.Set_Character_Character_R_UpperArm_Male_Torso_1
													}
												/>
											</group>
											<primitive
												object={
													nodes.Set_Character_Character_R_Clavicle_Male_Torso_1
												}
											/>
										</group>
										<primitive
											object={nodes.Set_Character_Character_Spine2_Male_Torso_1}
										/>
									</group>
									<primitive
										object={nodes.Set_Character_Character_Spine1_Male_Torso_1}
									/>
								</group>
								<primitive
									object={nodes.Set_Character_Character_Spine_Male_Legs_1}
								/>
								<primitive
									object={nodes.Set_Character_Character_Spine_Male_Torso_1}
								/>
							</group>
							<primitive
								object={nodes.Set_Character_Character_Pelvis_Male_Legs_1}
							/>
							<primitive
								object={nodes.Set_Character_Character_Pelvis_Male_Torso_1}
							/>
						</group>
						<group name="Set_Character_Character_Male_Legs_1" />
						<group name="Set_Character_Character_Male_Torso_1" />
					</group>
					<group name="Set_Character_Male_Legs_1">
						<skinnedMesh
							name="Set_Character_Male_Legs_1_1"
							geometry={nodes.Set_Character_Male_Legs_1_1.geometry}
							material={materials.Male_Legs_1_Black}
							skeleton={nodes.Set_Character_Male_Legs_1_1.skeleton}
							morphTargetDictionary={
								nodes.Set_Character_Male_Legs_1_1.morphTargetDictionary
							}
							morphTargetInfluences={
								nodes.Set_Character_Male_Legs_1_1.morphTargetInfluences
							}
							rotation={[-Math.PI / 2, 0, 0]}
						/>
					</group>
					<group name="Set_Character_Male_Torso_1">
						<group
							name="Set_Character_Male_Torso_1_1"
							rotation={[-Math.PI / 2, 0, 0]}
						>
							<skinnedMesh
								name="Set_Character_Male_Torso_1_2"
								geometry={nodes.Set_Character_Male_Torso_1_2.geometry}
								material={materials.Male_Torso_1_Blue}
								skeleton={nodes.Set_Character_Male_Torso_1_2.skeleton}
								morphTargetDictionary={
									nodes.Set_Character_Male_Torso_1_2.morphTargetDictionary
								}
								morphTargetInfluences={
									nodes.Set_Character_Male_Torso_1_2.morphTargetInfluences
								}
							/>
							<skinnedMesh
								name="Set_Character_Male_Torso_1_3"
								geometry={nodes.Set_Character_Male_Torso_1_3.geometry}
								material={materials.Male_Torso_1_Skin_Light}
								skeleton={nodes.Set_Character_Male_Torso_1_3.skeleton}
								morphTargetDictionary={
									nodes.Set_Character_Male_Torso_1_3.morphTargetDictionary
								}
								morphTargetInfluences={
									nodes.Set_Character_Male_Torso_1_3.morphTargetInfluences
								}
							/>
						</group>
					</group>
					<group name="Set_Character_Male_Head_1" scale={0.99}>
						<skinnedMesh
							name="Set_Character_Male_Head_1_1"
							geometry={nodes.Set_Character_Male_Head_1_1.geometry}
							material={materials.Male_Head_1}
							skeleton={nodes.Set_Character_Male_Head_1_1.skeleton}
							morphTargetDictionary={
								nodes.Set_Character_Male_Head_1_1.morphTargetDictionary
							}
							morphTargetInfluences={
								nodes.Set_Character_Male_Head_1_1.morphTargetInfluences
							}
							position={[0, 1.53, -0.03]}
							rotation={[Math.PI / 2, Math.PI / 2, 0]}
						/>
					</group>
				</group>
			</group>
		</group>
	);
}

useGLTF.preload("/MaleC.glb");
