/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function FemaleHairOne(props) {
	const { nodes, materials } = useGLTF("/FemaleHairOne.glb");

	return (
		<group {...props} dispose={null}>
			<group position={[0, 0, 1]}>
				<primitive object={nodes.Character_Head} />
				<skinnedMesh
					name="Female_Hair_1_1"
					geometry={nodes.Female_Hair_1_1.geometry}
					material={materials.Female_Hair_1}
					skeleton={nodes.Female_Hair_1_1.skeleton}
					morphTargetDictionary={nodes.Female_Hair_1_1.morphTargetDictionary}
					morphTargetInfluences={nodes.Female_Hair_1_1.morphTargetInfluences}
					position={[0, 1.42, -0.04]}
					rotation={[Math.PI / 2, Math.PI / 2, 0]}
				/>
			</group>
		</group>
	);
}

useGLTF.preload("/FemaleHairOne.glb");
